env:
  id: LunarLanderContinuous-v2
  max_episode_steps: 1000
  reward_threshold: 200

seed: 42

agent:
  gamma: 0.99        # Discount factor
  tau: 0.005         # Target network soft update rate
  actor_lr: 1e-3     # Actor learning rate
  critic_lr: 1e-3    # Critic learning rate
  batch_size: 100
  buffer_size: 1000000

training:
  max_episodes: 1000
  max_timesteps: 1000
  policy_delay: 2     # Delayed policy update freq (TD3 feature)

exploration:
  noise_std_dev: 0.2
  noise_clip: 0.5
